language: php
install: composer install
cache:
  directories:
    -vendor

sudo: false

php:
  - 5.5
  
env:
  - DB=mysql

before_script:
  - echo "Before Script"
  - composer show --installed
  - date
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash
  - ./vendor/bin/phpcs --config-set installed_paths $(pwd)/vendor/cakephp/cakephp-codesniffer

script:
  - echo "Running test script"
  - date
  - env
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot"
  - ./vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./src

notifications:
  email: lecaoquochung@gmail.com
